//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Editor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Editor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageEditor.Resources.Editor", typeof(Editor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Brush.
        /// </summary>
        public static string ACTIVATE_BRUSH {
            get {
                return ResourceManager.GetString("ACTIVATE_BRUSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated.
        /// </summary>
        public static string ACTIVATED {
            get {
                return ResourceManager.GetString("ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Text.
        /// </summary>
        public static string ADD_TEXT {
            get {
                return ResourceManager.GetString("ADD_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string BLUE {
            get {
                return ResourceManager.GetString("BLUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blur.
        /// </summary>
        public static string BLUR {
            get {
                return ResourceManager.GetString("BLUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        public static string BRIGHTNESS {
            get {
                return ResourceManager.GetString("BRIGHTNESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush.
        /// </summary>
        public static string BRUSH {
            get {
                return ResourceManager.GetString("BRUSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Size.
        /// </summary>
        public static string BRUSH_SIZE {
            get {
                return ResourceManager.GetString("BRUSH_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collage.
        /// </summary>
        public static string COLLAGE {
            get {
                return ResourceManager.GetString("COLLAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Adjustments.
        /// </summary>
        public static string COLOR_ADJUSTMENTS {
            get {
                return ResourceManager.GetString("COLOR_ADJUSTMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast.
        /// </summary>
        public static string CONTRAST {
            get {
                return ResourceManager.GetString("CONTRAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop.
        /// </summary>
        public static string CROP {
            get {
                return ResourceManager.GetString("CROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Text.
        /// </summary>
        public static string DELETE_TEXT {
            get {
                return ResourceManager.GetString("DELETE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Text.
        /// </summary>
        public static string EDIT_TEXT {
            get {
                return ResourceManager.GetString("EDIT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter image height.
        /// </summary>
        public static string ENTER_IMAGE_HEIGHT {
            get {
                return ResourceManager.GetString("ENTER_IMAGE_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter image width.
        /// </summary>
        public static string ENTER_IMAGE_WIDTH {
            get {
                return ResourceManager.GetString("ENTER_IMAGE_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text here.
        /// </summary>
        public static string ENTER_TEXT_HERE {
            get {
                return ResourceManager.GetString("ENTER_TEXT_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip.
        /// </summary>
        public static string FLIP {
            get {
                return ResourceManager.GetString("FLIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string FONT_SIZE {
            get {
                return ResourceManager.GetString("FONT_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string GREEN {
            get {
                return ResourceManager.GetString("GREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights.
        /// </summary>
        public static string HIGHLIGHT {
            get {
                return ResourceManager.GetString("HIGHLIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue.
        /// </summary>
        public static string HUE {
            get {
                return ResourceManager.GetString("HUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Editor.
        /// </summary>
        public static string IMAGE_EDITOR {
            get {
                return ResourceManager.GetString("IMAGE_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File.
        /// </summary>
        public static string INVALID_FILE {
            get {
                return ResourceManager.GetString("INVALID_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum limit of 2 images reached for collage.
        /// </summary>
        public static string MAX_LIMIT_2 {
            get {
                return ResourceManager.GetString("MAX_LIMIT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum limit of 4 images reached for collage.
        /// </summary>
        public static string MAX_LIMIT_4 {
            get {
                return ResourceManager.GetString("MAX_LIMIT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror.
        /// </summary>
        public static string MIRROR {
            get {
                return ResourceManager.GetString("MIRROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select image.
        /// </summary>
        public static string PLEASE_SELECT_IMAGE {
            get {
                return ResourceManager.GetString("PLEASE_SELECT_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string RED {
            get {
                return ResourceManager.GetString("RED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Editing.
        /// </summary>
        public static string RESET_EDITING {
            get {
                return ResourceManager.GetString("RESET_EDITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        public static string RESIZE {
            get {
                return ResourceManager.GetString("RESIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        public static string ROTATE {
            get {
                return ResourceManager.GetString("ROTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation.
        /// </summary>
        public static string SATURATION {
            get {
                return ResourceManager.GetString("SATURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid image file.
        /// </summary>
        public static string SELECT_VALID_IMAGE {
            get {
                return ResourceManager.GetString("SELECT_VALID_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadows.
        /// </summary>
        public static string SHADOWS {
            get {
                return ResourceManager.GetString("SHADOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpness.
        /// </summary>
        public static string SHARPNESS {
            get {
                return ResourceManager.GetString("SHARPNESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Effects.
        /// </summary>
        public static string SPECIAL_EFFECTS {
            get {
                return ResourceManager.GetString("SPECIAL_EFFECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SUBMIT {
            get {
                return ResourceManager.GetString("SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string TEMPERATURE {
            get {
                return ResourceManager.GetString("TEMPERATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        public static string TEMPLATES {
            get {
                return ResourceManager.GetString("TEMPLATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string TEXT {
            get {
                return ResourceManager.GetString("TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonal Adjustments.
        /// </summary>
        public static string TONAL_ADJUSTMENTS {
            get {
                return ResourceManager.GetString("TONAL_ADJUSTMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformation.
        /// </summary>
        public static string TRANSFORMATION {
            get {
                return ResourceManager.GetString("TRANSFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string UNDO {
            get {
                return ResourceManager.GetString("UNDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string UPLOAD {
            get {
                return ResourceManager.GetString("UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrance.
        /// </summary>
        public static string VIBRANCE {
            get {
                return ResourceManager.GetString("VIBRANCE", resourceCulture);
            }
        }
    }
}
